/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'timestamp' : IDL.Int,
  'locationLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteLocation' : IDL.Func([IDL.Text], [], []),
  'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
  'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listLocationsByLat' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listLocationsByLng' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'listLocationsSortByTimestamp' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'shareLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'timestamp' : IDL.Int,
    'locationLabel' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteLocation' : IDL.Func([IDL.Text], [], []),
    'getLocation' : IDL.Func([IDL.Text], [IDL.Opt(Location)], ['query']),
    'listLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listLocationsByLat' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listLocationsByLng' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'listLocationsSortByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'shareLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };